name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag argocd
    - name: Get CMD
      run: docker run -d --rm --name argocd argocd tail -f /dev/null
    - name: GET
      run: docker exec -it argocd ls -alh
    - name: RM
      run: docker stop argocd
